### PR TITLE
Add Makefile ,Github action and Update Readme(#Build)

### PR DESCRIPTION
**Pull request by powenn**
latest action 
https://github.com/powenn/Notch-Simulator/actions/runs/1403824839

Makefile works fine
build from Github action have larger file size than from Makefile,about 0.3~0.4 mb, it doesn't effect to install and run 
it cause by several unnecessary framework ,can be delete by add rm -rf command in build.yml

### CODE REVIEW

**Comment by megabitsenmzq** [comment]
This is just my side project. I don't want to use GitHub action. I think it's a little bit overkill. But still thank you so much.

**Comment by powenn** [comment]
> This is just my side project. I don't want to use GitHub action. I think it's a little bit overkill. But still thank you so much.

okay, how about Makefile

**Comment by megabitsenmzq** [comment]
Because I still need to upload the archive to Apple for Notarize. I don't see the point to have a build file. And 2.0 might be the final version of this project. There won't be any updates for a long time.

**Comment by powenn** [comment]
> Because I still need to upload the archive to Apple for Notarize. I don't see the point to have a build file. And 2.1 might be the final version of this project. There won't be any updates for a long time.

It's for testing without sign ,only one command and will get package

**Comment by megabitsenmzq** [comment]
Why not just download the release? I still don't think this is the kind of project that needs to have these things. This project is just a meme. I don't want to add more complexity. Still, thank you very much.

**Comment by powenn** [comment]
> Why not just download the release? I still don't think this is the kind of project that needs to have these things. This project is just a meme. I don't want to add more complexity. Still, thank you very much.

Got it,just thought that maybe someone will feel interest to try something then he might need

**Pull request closed without merging**
